# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: gloomyghost.com
date_format: "ordinal"
name: "GloomyGhost"
title: GloomyGhost
subtitle: "GloomyGhost's Blog>>Life Because You"
description: "GloomyGhost's Blog"
keywords: GloomyGhost,blog
favicon: /favicon.ico
# timezone: Asia/YunNan
encoding: "utf-8"
side_bar_repo_limit: 6

# ---------------- #
#      Author      #
# ---------------- #
author: GloomyGhost
github_username: GloomyGhost
location: YunNan, China
email: GloomyGhost@foxmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 主页

  -
    href: /links/
    label: 友链

  -
    href: /projects/
    label: 作品

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
auto: true
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: 740291272/740291272.github.io

