# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: gloomyghost.com
date_format: "ordinal"
name: "GloomyGhost's Blog"
title: GloomyGhost's Blog
subtitle: "emmmmmmmm"
description: "GloomyGhost's Blog"
keywords: GloomyGhost,blog
favicon: /favicon.ico
# timezone: Asia/YunNan
encoding: "utf-8"
side_bar_repo_limit: 6

# ---------------- #
#      Author      #
# ---------------- #
author: GloomyGhost
github_username: GloomyGhost
github_username2: 740291272/740291272.github.io
location: YunNan, China
email: GloomyGhost@foxmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 主页


  -
    href: /gloomyghost/tools/index.html
    label: 工具

  -
    href: /categories/
    label: 归档

  -
    href: /pages/repo.html
    label: 评论

  -
    href: /links/
    label: 友链

  -
    href: https://github.com/740291272
    label: 作品

  -
    href: https://gloomgyghost.github.io/
    label: English
# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml


# ---------------- #
#      Repo        #
# ---------------- #


gitment:
  on: true  # 启用gitment评论系统
  owner: 740291272  # 你的github账号
  repo: REPO  # 评论issue保存的仓库，我选择保存在blog仓库，也可以新建一个仓库
  client_id: 372fd5e862e90d77b1b6   # 上一步注册后生成的client_id
  client_secret: cd16646f856da1331e62653765be34e0e07c9a84 # 上一步注册后生成的client_secret




# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
auto: true
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: 740291272/740291272.github.io

